export const photos = [
  {
    src: "/suits/111.jpg",
    title: "slider image",
    alt: "slider image",
    width: 3,
    height: 2,
  },
  {
    src: "/suits/115.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/116.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/112.jpg",
    title: "slider image",
    alt: "slider image",
    width: 3,
    height: 2,
  },
  {
    src: "/suits/117.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/118.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/113.jpg",
    title: "slider image",
    alt: "slider image",
    width: 3,
    height: 2,
  },
  {
    src: "/suits/114.jpg",
    title: "slider image",
    alt: "slider image",
    width: 3,
    height: 2,
  },
  {
    src: "/suits/119.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/120.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/121.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/122.jpg",
    title: "slider image",
    alt: "slider image",
    width: 2,
    height: 3,
  },
  {
    src: "/suits/123.jpg",
    title: "slider image",
    alt: "slider image",
    width: 3,
    height: 2,
  },
];
